---
title: "figures.supplementary_figure_5.Misty"
author: "FloWuenne"
date: "2024-02-15"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction


```{r}
library(Seurat)
#options(Seurat.object.assay.version = 'v5')
library(tidyverse)
library(scales)
library(pals)
library(patchwork)
library(mistyR)
library(ClusterR)
library(future)
library(ggbeeswarm)
library(ggdark)

source("./code/functions.R")
```


# Load data

```{r}
misty.results.g <- readRDS("./output/molkart/misty_results.lowres.125.rds")
```

```{r}
data_list <- list()
plot_list <-list()

measure.type <- "gain.R2"
inv <- sign((stringr::str_detect(measure.type, "gain") |
    stringr::str_detect(measure.type, "RMSE", negate = TRUE)) - 0.5)
trim = -Inf
conditions <- c("control","4h","2d","4d")
for(condition in conditions){
  misty_results <- misty.results.g[[condition]]
  plot.data <- misty_results$improvements.stats %>%
    dplyr::filter(measure == measure.type, inv * mean >= inv * trim)
  plot.data$condition <- condition 
  data_list[[condition]] <- plot.data
}
```

```{r}
library(tidytext)
full_table <- do.call("rbind", data_list)
full_table <- full_table %>%
  mutate(target = reorder_within(target, -mean, condition))
full_table$condition <- factor(full_table$condition,
                               levels = c("control","4h","2d","4d"))

set2.orange <- "#FC8D62"
results.plot <- ggplot2::ggplot(
    full_table,
    ggplot2::aes(
      x = target,
      y = mean
    )
  ) +
  ggplot2::geom_pointrange(ggplot2::aes(
    ymin = mean - sd,
    ymax = mean + sd
  )) +
  scale_x_reordered() +
  ggplot2::geom_point(color = set2.orange) +
  ggplot2::theme_classic() +
  ggplot2::ylab(measure.type) +
  ggplot2::xlab("Target") +
  ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, hjust = 1)) + 
  facet_grid(.~condition,scales = "free")
results.plot

save_plot(results.plot,
          file = "./plots/Supplementary_Figure5.mistyR_gains.png",
          base_height = 4)
```


```{r}
final_plot <- patchwork::wrap_plots(plotlist = plot_list, ncol = 1)
final_plot
```

