---
title: "figures.supplementary_figure4"
author: "FloWuenne"
date: "2023-09-04"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r}
library(Seurat)
library(tidyverse)
library(ggpubr)
library(cowplot)
library(patchwork)
```


# Read data

```{r}
## If the object has already been computed
seurat_object <- readRDS(file = "./output/mol_cart/molkart.harmony_seurat_object.rds")
```

# Subfigure A - Total number of cells per sample

```{r}
meta <- seurat_object@meta.data

cells_per_time <- meta %>%
  group_by(timepoint,sample_ID) %>%
  tally()

cells_per_time_plot <- ggbarplot(cells_per_time, 
          x = "timepoint",
          y = "n",
          add = c("mean", "dotplot"), 
          fill = "timepoint", color = "black",
          palette = "Dark2") +
   labs (x = "Time",
         y = "Total cells") +
  font("xlab", size = 16, color = "black", face = "bold") +
  font("ylab", size = 16, color = "black", face = "bold") +
    scale_y_continuous(
    # don't expand y scale at the lower end
    expand = expansion(mult = c(0, 0.05))
  ) +
  #theme_minimal_hgrid() +
  theme(axis.title = element_text(face="bold")) +
  rremove("legend")
```

# Subfigure B - Distribution of cells in UMAP by time


```{r}
dimplot_time <- SCpubr::do_DimPlot(sample = seurat_object,
                   label = FALSE, label.box = FALSE,
                   split.by = "timepoint", 
                   ncol = 3,
                  legend.position = "none",
                  font.size = 24,
                  colors.use = )
```

# Combine plots

```{r}
cobmined_plots <- cells_per_time_plot / dimplot_time 

save_plot(cobmined_plots,
          file = "./figures/figures.supplementary_figure4.png",
          base_height = 8,
          base_asp = 1.3)
```

