---
title: "analyze_masks"
author: "FloWuenne"
date: "2023-07-28"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r}
library(Giotto)
library(GiottoData)
library(data.table)

genv_exists = checkGiottoEnvironment()
if(!genv_exists){
  # The following command need only be run once to install the Giotto environment.
  installGiottoEnvironment()
}
```

# Creating a Giotto object from scratch

```{r}
data_directory = ("/Users/florian_wuennemann/Downloads/")
results_directory = data_directory
```


```{r}
# Specify data with file paths
osm_exprs = paste0(data_directory, "osmFISH_prep_expression.txt")
osm_locs = paste0(data_directory, "osmFISH_prep_cell_coordinates.txt")
meta_path = paste0(data_directory, "osmFISH_prep_cell_metadata.txt")

# Create instructions

# Optional: Specify a path to a Python executable within a conda or miniconda
# environment. If set to NULL (default), the Python executable within the previously
# installed Giotto environment will be used.
my_python_path = NULL # alternatively, "/local/python/path/python" if desired.

instrs = createGiottoInstructions(python_path = my_python_path,
                                  save_dir = results_directory,
                                  plot_format = 'png',
                                  dpi = 200,
                                  height = 9,
                                  width = 9)

# Create Giotto object
custom_gobject = createGiottoObject(expression = osm_exprs,
                                    spatial_locs = osm_locs,
                                    instructions = instrs)

# Add field annotations as cell metadata
metadata = data.table::fread(file = meta_path)
custom_gobject = addCellMetadata(custom_gobject, new_metadata = metadata,
                                 by_column = T, column_cell_ID = 'CellID')

# Show the Giotto instructions associated with the Giotto object
instructions(custom_gobject)
```

```{r}
# Plot clusters, create, and save to a new subdirectory, all while overwriting formatting
spatPlot(custom_gobject,
         cell_color = 'ClusterName',
         save_plot = TRUE,
         return_plot = TRUE,
         show_plot = TRUE,
         save_param = list(save_folder = 'plots/', # Create subdirectory
                           save_name = 'cell_clusters',
                           save_format = 'png',
                           units = 'in',
                           base_height = 9,
                           base_width = 9))

```



# Giotto example

## Load data

```{r}
my_working_dir = './analysis'

# Creating Giotto Instructions without specifying a Python path will make
# reticulate activate the default Giotto environment.
default_instrs <- createGiottoInstructions()
```

```{r}
## provide path to resolve bioscience folder
data_path = '../data/nf_molkart_results'
my_python_path = NULL

# 1. original image as png
original_DAPI_image = "/Users/florian_wuennemann/1_Projects/MI_project/data/molcart_AB_stains/sample_control_r1_s1.DAPI.jpeg"

# 2. input cell segmentation as mask file
# can also be provided as a 3-column polygon file
# to be used as image background AND to store segmentations as polygons
# can be obtained through Fiji / QuPath / Ilastik / Cellpose / ...
segmentation_mask = paste0(data_path, '/retained_masks/', 'sample_control_r1_s1_cellpose.retained_masks.16bit.png')

# 3. input features coordinates
tx_coord = fread(paste0(data_path, '/dedup_spots/', 'sample_control_r1_s1.spots_markedDups.txt'))
colnames(tx_coord) = c('x', 'y', 'z', 'gene_id')
tx_coord = tx_coord[,.(x, y, gene_id)]
```

## Part 1: Create Subcellular Giotto Object

```{r}
testobj = createGiottoObjectSubcellular(gpoints = list('rna' = tx_coord),
                    gpolygons = list('cell' = segmentation_mask),
                    instructions = default_instrs,
                    verbose = FALSE,
                    cores = 16)
```

## Part 2: Create Spatial Locations

```{r}
# centroids are now used to provide the spatial locations (centroid of each cell)
# needed for certain downstream spatial analyses
testobj = addSpatialCentroidLocations(testobj,
                    poly_info = 'cell')
```

## Part 3: Add Image Information

```{r}
# create Giotto images
DAPI_image = createGiottoImage(gobject = testobj,
                name = 'DAPI',
                do_manual_adj = T,
                xmax_adj = 0,ymax_adj = 0,
                xmin_adj = 0,ymin_adj = 0,
                image_transformations = 'flip_x_axis',
                mg_object = original_DAPI_image)
DAPI_boundaries <- c("xmax_adj" = 0, "xmin_adj" = 0,
	"ymax_adj" = 0,	"ymin_adj" = 0)
DAPI_image@boundaries <- DAPI_boundaries

segm_image = createGiottoImage(gobject = testobj,
                name = 'segmentation',
                do_manual_adj = T,
                xmax_adj = 0,ymax_adj = 0,
                xmin_adj = 0,ymin_adj = 0,
                image_transformations = 'flip_x_axis',
                mg_object = segmentation_mask)

# add images to Giotto object
testobj = addGiottoImage(testobj,
            images = list(DAPI_image, segm_image))

# provides an overview of available images
showGiottoImageNames(testobj)
```

## Part 4: Visualize Original Images

```{r}
# visualize overlay of calculated cell centroid with original image and segmentation mask file
 # by setting show_plot to FALSE and save_plot to TRUE you can save quite some time when creating plots
 # with big images it sometimes takes quite long for R/Rstudio to render them
 
spatPlot2D(gobject = testobj, image_name = 'DAPI', point_size = 1.5, save_plot = F, show_image = TRUE)
```


```{r}
spatPlot2D(gobject = testobj, image_name = 'segmentation', point_size = 1.5,
           show_image = TRUE)
```

## Part 5: Calculate Cell Shape Overlap

```{r}
tictoc::tic()
testobj = calculateOverlapParallel(testobj,
            spatial_info = 'cell',
            feat_info = 'rna')
tictoc::toc()
#convert overlap to matrix
testobj = overlapToMatrix(testobj,
            poly_info = 'cell',
            feat_info = 'rna',
            name = 'raw')
```

## Part 6: Filter Data

```{r}
# features can be filtered individually
# cells will be filtered across features

# first filter on rna
subc_test <- filterGiotto(gobject = testobj,
            expression_threshold = 1,
            feat_det_in_min_cells = 20,
            min_det_feats_per_cell = 5)

spatPlot2D(gobject = subc_test,
    image_name = 'segmentation', show_image = TRUE,
    point_size = 1.5)

```


## Part 7: Normalize data



## Part 8: Dimension Reduction

```{r}
# rna data, default.
 # other feature modalities can be processed and filtered in an anologous manner
 subc_test <- normalizeGiotto(gobject = subc_test, scalefactor = 6000, verbose = T)
 subc_test <- addStatistics(gobject = subc_test)
 subc_test <- adjustGiottoMatrix(gobject = subc_test,
                 expression_values = c('normalized'),
                 covariate_columns = c('nr_feats', 'total_expr'))

 subc_test <- normalizeGiotto(gobject = subc_test, norm_methods = 'pearson_resid', update_slot = 'pearson')
 showGiottoExpression(subc_test)
```


```{r}
# Find highly valuable Features

# typical way of calculating HVF
subc_test <- calculateHVF(gobject = subc_test, HVFname= 'hvg_orig')
```

