---
title: "Data analysis"
author: "Florian Wuennemann"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Molecular Cartography

These scripts were used to analyze Molecular Cartography data following processing with the nf-Molkart pipeline.

## Raw RNA spot analysis

- [Quantification of RNA spots on tissue](https://github.com/SchapiroLabor/mi_spatialomics/blob/main/analysis/molecular_cartography_python/molkart.count_spots_on_tissue.ipynb)
- [QC RNA spots](./molkart.QC_spots.html)   

## Cell type calling

- [Seurat analysis of Molkart output](./molkart.seurat_analysis.html)
- [Misty spatial analysis](./molkart.misty_analysis.html)
- [Liana bivariate cell-type analysis](https://github.com/SchapiroLabor/mi_spatialomics/blob/main/analysis/molecular_cartography_python/molkart.local_analysis_lianaplus.ipynb)

# Lunaphore

These scripts were used to analyze SeqIF data from the Lunaphore COMET platform processed using MCMICRO and pixie.

1) [Pixie : Marker images, pixel and cell clusters using Napari](https://github.com/SchapiroLabor/mi_spatialomics/blob/main/analysis/seqIF_python/seqIF.figure_3.create_pixie_images.ipynb)
2) [Pixie : Heatmaps for pixel and cell clustering and cell cluster changes over time](./seqIF.heatmaps_pixie.figure3.html)

# Laser-microdissection coupled with high-sensitivity proteomics (Deep Visual Proteomics)

1) [Filter proteomic data](./proteomics.filter_proteomic_data.html)
2) [Identification of differentially expressed proteins (DEPs)](./proteomics.bulk_de_analysis.html)
3) [Pathway enrichment analysis of DEPs](./proteomics.pathway_enrichment_analysis.html)
4) [Comparing snRNA-seq data with proteomic data](./proteomics.scRNAseq_comparison.html)
