---
title: "mol_cart.Figure2"
author: "FloWuenne"
date: "2023-09-01"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r}
library(Seurat)
#options(Seurat.object.assay.version = 'v5')
library(tidyverse)
library(scales)
library(pals)
library(patchwork)
library(mistyR)
library(ClusterR)
library(future)
library(ggbeeswarm)
library(ggdark)

source("./code/functions.R")
```

# Load data

```{r}
misty.results.g <- readRDS("./output/molkart/misty_results.lowres.125.rds")
```


# Figure 2A,D,G : Plot Misty interaction matrix

## With labels

```{r}
## Misty plots with labels
plot_interaction_heatmap_custom <- function(misty.results, view, cutoff = 1,
                                     trim = -Inf, trim.measure = c(
                                       "gain.R2", "multi.R2", "intra.R2",
                                       "gain.RMSE", "multi.RMSE", "intra.RMSE"
                                     ),
                                     clean = FALSE) {
  trim.measure.type <- match.arg(trim.measure)

  assertthat::assert_that(("importances.aggregated" %in% names(misty.results)),
    msg = "The provided result list is malformed. Consider using collect_results()."
  )

  assertthat::assert_that(("improvements.stats" %in% names(misty.results)),
    msg = "The provided result list is malformed. Consider using collect_results()."
  )

  assertthat::assert_that((view %in%
    (misty.results$importances.aggregated %>% dplyr::pull(view))),
  msg = "The selected view cannot be found in the results table."
  )

  inv <- sign((stringr::str_detect(trim.measure.type, "gain") |
    stringr::str_detect(trim.measure.type, "RMSE", negate = TRUE)) - 0.5)

  targets <- misty.results$improvements.stats %>%
    dplyr::filter(
      measure == trim.measure.type,
      inv * mean >= inv * trim
    ) %>%
    dplyr::pull(target)


  plot.data <- misty.results$importances.aggregated %>%
    dplyr::filter(view == !!view, Target %in% targets)

  if (clean) {
    clean.predictors <- plot.data %>%
      dplyr::mutate(Importance = Importance * (Importance >= cutoff)) %>%
      dplyr::group_by(Predictor) %>%
      dplyr::summarize(total = sum(Importance, na.rm = TRUE)) %>%
      dplyr::filter(total > 0) %>%
      dplyr::pull(Predictor)
    clean.targets <- plot.data %>%
      dplyr::mutate(Importance = Importance * (Importance >= cutoff)) %>%
      dplyr::group_by(Target) %>%
      dplyr::summarize(total = sum(Importance, na.rm = TRUE)) %>%
      dplyr::filter(total > 0) %>%
      dplyr::pull(Target)
    plot.data.clean <- plot.data
    # plot.data.clean <- plot.data %>%
    #   dplyr::filter(
    #     Predictor %in% clean.predictors,
    #     Target %in% clean.targets
    #   )
  } else {
    plot.data.clean <- plot.data
  }

  #set2.blue <- "#8DA0CB"
  ## Color roughly based on https://icolorpalette.com/color/080210
  
  
  ## Replace dots with spaces in cell type names
  plot.data.clean$Predictor <- gsub("\\."," ",plot.data.clean$Predictor)
  plot.data.clean$Target <- gsub("\\."," ",plot.data.clean$Target)
  
  plot.data.clean$Predictor <- gsub("Cardiomyocytes Nppa ","Cardiomyocytes Nppa+",plot.data.clean$Predictor)
  plot.data.clean$Target <- gsub("Cardiomyocytes Nppa ","Cardiomyocytes Nppa+",plot.data.clean$Target) 
  
  ## Subset for only relevant Predictors
  plot.data.clean <- subset(plot.data.clean,Predictor %in% c("Cardiomyocytes","Cardiomyocytes Nppa+","Endocardial cells",
                                                             "Cardiac fibroblasts","Pericytes","Myeloid cells"))
  
  ## Subset for only interactions above specified threshold 
  plot.data.clean <- plot.data.clean %>%
    mutate("Importance" = ifelse(Importance < cutoff, 0, Importance))
  
  ## Plot data
  results.plot <- ggplot2::ggplot(
    plot.data.clean,
    ggplot2::aes(
      x = Predictor,
      y = Target
    )
  ) +
    #ggplot2::geom_tile(data = subset(plot.data.clean, Importance > cutoff),ggplot2::aes(fill = Importance)) +
    ggplot2::geom_tile(ggplot2::aes(fill = Importance)) +
    ggplot2::scale_fill_gradientn(
      colours = c("white", "#efe5fb", "#d3baf6", "#691ad2","#5314a6","#27094f"),
      #values = scales::rescale(c(0, 0.5, 1, 1.2)),
      limits = c(0,1.8)
    ) +
    # ggplot2::scale_fill_gradient2(

    #   limits = c(0, max(plot.data.clean$Importance))
    # ) +
    ggplot2::theme_classic() +
    ggplot2::theme(axis.title = ggplot2::element_text(size = 20),
                   axis.text.x = ggplot2::element_text(angle = 90, hjust = 1, size = 15),
                   axis.text.y = ggplot2::element_text(size = 15),
                   legend.title = ggplot2::element_text(size = 15),
                   legend.text = ggplot2::element_text(size = 15)) +
    ggplot2::coord_equal() 
    #ggplot2::ggtitle(view)

  return(results.plot)
  #return(plot.data.clean)

  invisible(misty.results)
}

## Now we will plot the interaction heatmap
control_misty <- plot_interaction_heatmap_custom(misty.results.g$control, "paraview", cutoff = 0.4, clean = TRUE, trim = 5)

control_misty

save_plot(control_misty,
          file = "./plots/Figure2.mistyR_control.with_labels.pdf",
          base_height = 7)


d2_misty <- plot_interaction_heatmap_custom(misty.results.g$'2d', "paraview", cutoff = 0.4, clean = TRUE, trim = 5)

d2_misty

save_plot(d2_misty,
          file = "./plots/Figure2.mistyR_d2.with_labels.pdf",
          base_height = 5)

d4_misty <- plot_interaction_heatmap_custom(misty.results.g$'4d', "paraview", cutoff = 0.4, clean = TRUE, trim = 5)

d4_misty

save_plot(d4_misty,
          file = "./plots/Figure2.mistyR_d4.with_labels.pdf",
          base_height = 5)
```


## Without labels

```{r}
## Misty figures without text for adding to Adobe
## Misty plots with labels
plot_interaction_heatmap_custom <- function(misty.results, view, cutoff = 1,
                                     trim = -Inf, trim.measure = c(
                                       "gain.R2", "multi.R2", "intra.R2",
                                       "gain.RMSE", "multi.RMSE", "intra.RMSE"
                                     ),
                                     clean = FALSE) {
  trim.measure.type <- match.arg(trim.measure)

  assertthat::assert_that(("importances.aggregated" %in% names(misty.results)),
    msg = "The provided result list is malformed. Consider using collect_results()."
  )

  assertthat::assert_that(("improvements.stats" %in% names(misty.results)),
    msg = "The provided result list is malformed. Consider using collect_results()."
  )

  assertthat::assert_that((view %in%
    (misty.results$importances.aggregated %>% dplyr::pull(view))),
  msg = "The selected view cannot be found in the results table."
  )

  inv <- sign((stringr::str_detect(trim.measure.type, "gain") |
    stringr::str_detect(trim.measure.type, "RMSE", negate = TRUE)) - 0.5)

  targets <- misty.results$improvements.stats %>%
    dplyr::filter(
      measure == trim.measure.type,
      inv * mean >= inv * trim
    ) %>%
    dplyr::pull(target)


  plot.data <- misty.results$importances.aggregated %>%
    dplyr::filter(view == !!view, Target %in% targets)

  if (clean) {
    clean.predictors <- plot.data %>%
      dplyr::mutate(Importance = Importance * (Importance >= cutoff)) %>%
      dplyr::group_by(Predictor) %>%
      dplyr::summarize(total = sum(Importance, na.rm = TRUE)) %>%
      dplyr::filter(total > 0) %>%
      dplyr::pull(Predictor)
    clean.targets <- plot.data %>%
      dplyr::mutate(Importance = Importance * (Importance >= cutoff)) %>%
      dplyr::group_by(Target) %>%
      dplyr::summarize(total = sum(Importance, na.rm = TRUE)) %>%
      dplyr::filter(total > 0) %>%
      dplyr::pull(Target)
    plot.data.clean <- plot.data
    # plot.data.clean <- plot.data %>%
    #   dplyr::filter(
    #     Predictor %in% clean.predictors,
    #     Target %in% clean.targets
    #   )
  } else {
    plot.data.clean <- plot.data
  }

  #set2.blue <- "#8DA0CB"
  ## Color roughly based on https://icolorpalette.com/color/080210
  
  
  ## Replace dots with spaces in cell type names
  plot.data.clean$Predictor <- gsub("\\."," ",plot.data.clean$Predictor)
  plot.data.clean$Target <- gsub("\\."," ",plot.data.clean$Target)
  
  plot.data.clean$Predictor <- gsub("Cardiomyocytes Nppa ","Cardiomyocytes Nppa+",plot.data.clean$Predictor)
  plot.data.clean$Target <- gsub("Cardiomyocytes Nppa ","Cardiomyocytes Nppa+",plot.data.clean$Target) 
  
  ## Subset for only relevant Predictors
  plot.data.clean <- subset(plot.data.clean,Predictor %in% c("Cardiomyocytes","Cardiomyocytes Nppa+","Endocardial cells",
                                                             "Cardiac fibroblasts","Pericytes","Myeloid cells"))
  
  ## Subset for only interactions above specified threshold 
  plot.data.clean <- plot.data.clean %>%
    mutate("Importance" = ifelse(Importance < cutoff, 0, Importance))
  
  ## Plot data
  results.plot <- ggplot2::ggplot(
    plot.data.clean,
    ggplot2::aes(
      x = Predictor,
      y = Target
    )
  ) +
    #ggplot2::geom_tile(data = subset(plot.data.clean, Importance > cutoff),ggplot2::aes(fill = Importance)) +
    ggplot2::geom_tile(ggplot2::aes(fill = Importance)) +
    ggplot2::scale_fill_gradientn(
      colours = c("white", "#efe5fb", "#d3baf6", "#691ad2","#5314a6","#27094f"),
      #values = scales::rescale(c(0, 0.5, 1, 1.2)),
      limits = c(0,1.8)
    ) +
    # ggplot2::scale_fill_gradient2(

    #   limits = c(0, max(plot.data.clean$Importance))
    # ) +
    ggplot2::theme_classic() +
    ggplot2::theme(axis.title = element_blank(),
                   axis.text.x = element_blank(),
                   axis.text.y = element_blank(),
                   legend.title = element_blank(),
                   legend.text = element_blank()) +
    ggplot2::coord_equal() 
    #ggplot2::ggtitle(view)

  return(results.plot)
  #return(plot.data.clean)

  invisible(misty.results)
}

## Now we will plot the interaction heatmap
control_misty <- plot_interaction_heatmap_custom(misty.results.g$control, "paraview", cutoff = 0.4, clean = TRUE, trim = 5)

control_misty

save_plot(control_misty,
          file = "./plots/Figure2.mistyR_control.pdf",
          base_height = 2.5)


d2_misty <- plot_interaction_heatmap_custom(misty.results.g$'2d', "paraview", cutoff = 0.4, clean = TRUE, trim = 5)

d2_misty

save_plot(d2_misty,
          file = "./plots/Figure2.mistyR_d2.pdf",
          base_height = 2.5)

d4_misty <- plot_interaction_heatmap_custom(misty.results.g$'4d', "paraview", cutoff = 0.4, clean = TRUE, trim = 5)

d4_misty

save_plot(d4_misty,
          file = "./plots/Figure2.mistyR_d4.pdf",
          base_height = 2.5)
```


# Figure 2 : Distribution of cell types of interest


<!-- # Potential supplementary figure with markers -->

<!-- ```{r} -->
<!-- library(data.table) -->

<!-- spots_control <- fread("../results/nf-core_molkart/mindagap/sample_control_r2_s1_sample_control_r2_s1.spots_markedDups.txt") -->
<!-- colnames(spots_control) <- c("X","Y","Z","gene") -->
<!-- nppa <- ggplot(spots_control,aes(X,Y)) + -->
<!--   geom_point(data = subset(spots_control,gene =="Pln"),color = "lightgrey",size = 0.00001) + -->
<!--   geom_point(data = subset(spots_control,gene =="Nppa"),color = "magenta",size = 0.00001) + -->
<!--   xlim(0,17152) + -->
<!--   ylim(0,8576) + -->
<!--   dark_theme_void() -->

<!-- myeloid <- ggplot(spots_control,aes(X,Y)) + -->
<!--   geom_point(data = subset(spots_control,gene =="C1qa"),color = "yellow",size = 0.00001) + -->
<!--   xlim(0,17152) + -->
<!--   ylim(0,8576) + -->
<!--   dark_theme_void() -->

<!-- endocard <- ggplot(spots_control,aes(X,Y)) + -->
<!--   geom_point(data = subset(spots_control,gene =="Npr3"),color = "cyan",size = 0.00001) + -->
<!--   xlim(0,17152) + -->
<!--   ylim(0,8576) + -->
<!--   dark_theme_void() -->

<!-- nppa | myeloid | endocard -->
<!-- ``` -->

<!-- ```{r} -->
<!-- spots_d2 <- fread("../results/nf-core_molkart/mindagap/sample_2d_r2_s1_sample_2d_r2_s1.spots_markedDups.txt") -->
<!-- colnames(spots_d2) <- c("X","Y","Z","gene") -->
<!-- nppa <- ggplot(spots_d2,aes(X,Y)) + -->
<!--   geom_point(data = subset(spots_d2,gene =="Nppa"),color = "magenta",size = 0.1) + -->
<!--   xlim(0,10720) + -->
<!--   ylim(0,25728) + -->
<!--   dark_theme_void() -->

<!-- myeloid <- ggplot(spots_d2,aes(X,Y)) + -->
<!--   geom_point(data = subset(spots_d2,gene =="C1qa"),color = "yellow",size = 0.1) + -->
<!--   xlim(0,10720) + -->
<!--   ylim(0,25728) + -->
<!--   dark_theme_void() -->

<!-- endocard <- ggplot(spots_d2,aes(X,Y)) + -->
<!--   geom_point(data = subset(spots_d2,gene =="Npr3"),color = "cyan",size = 0.1) + -->
<!--   xlim(0,10720) + -->
<!--   ylim(0,25728) + -->
<!--   dark_theme_void() -->

<!-- nppa | myeloid | endocard -->
<!-- ``` -->

<!-- ```{r} -->
<!-- spots_d4 <- fread("../results/nf-core_molkart/mindagap/sample_4d_r1_s1_sample_4d_r1_s1.spots_markedDups.txt") -->
<!-- colnames(spots_d4) <- c("X","Y","Z","gene") -->
<!-- nppa <- ggplot(spots_d4,aes(X,Y)) + -->
<!--   geom_point(data = subset(spots_d4,gene =="Nppa"),color = "magenta",size = 0.1) + -->
<!--   xlim(0,15008) + -->
<!--   ylim(0,19296) + -->
<!--   dark_theme_void() -->

<!-- myeloid <- ggplot(spots_d4,aes(X,Y)) + -->
<!--   geom_point(data = subset(spots_d4,gene =="C1qa"),color = "yellow",size = 0.1) + -->
<!--   xlim(0,15008) + -->
<!--   ylim(0,19296) + -->
<!--   dark_theme_void() -->

<!-- endocard <- ggplot(spots_d4,aes(X,Y)) + -->
<!--   geom_point(data = subset(spots_d4,gene =="Npr3"),color = "cyan",size = 0.1) + -->
<!--   xlim(0,15008) + -->
<!--   ylim(0,19296) + -->
<!--   dark_theme_void() -->

<!-- nppa | myeloid | endocard -->
<!-- ``` -->


<!-- # Figure 2A:  Plot whole tissue quantification changes across time -->

<!-- ```{r} -->
<!-- metadata <- seurat_object@meta.data -->

<!-- cell_type_proportions_per_sample <- metadata %>% -->
<!--   group_by(anno_cell_type_lv2,timepoint,sample_ID) %>% -->
<!--   tally() %>% -->
<!--   ungroup() %>% -->
<!--   group_by(timepoint) %>% -->
<!--   mutate("ct_perc_time" = n / sum(n)) %>% -->
<!--   ungroup() -->

<!-- ## Mean and points version -->
<!-- cell_type_proportions_per_sample$anno_cell_type_lv2 <- gsub("_"," ",cell_type_proportions_per_sample$anno_cell_type_lv2) -->

<!-- ## Set order of cell types in plot from most abundant to least abundant -->
<!-- total_cells <- cell_type_proportions_per_sample %>% -->
<!--   group_by(anno_cell_type_lv2) %>% -->
<!--   summarise("total_cells" = sum(n)) %>% -->
<!--   arrange(desc(total_cells)) -->

<!-- cell_type_proportions_per_sample$anno_cell_type_lv2 <- factor(cell_type_proportions_per_sample$anno_cell_type_lv2, -->
<!--        levels = total_cells$anno_cell_type_lv2) -->

<!-- ## Set color palette for cell-types in molecular cartography data -->
<!-- arr <- list(x = -10, y = -15, x_len = 5, y_len = 5) -->
<!-- cell_types <- unique(unique(cell_type_proportions_per_sample$anno_cell_type_lv2)) -->
<!-- colors <- cols25(n=length(cell_types)) -->
<!-- named_colors <- colors -->
<!-- names(named_colors) <- cell_types -->

<!-- ct_time_barplot_v2 <- ggplot(cell_type_proportions_per_sample,aes(x = timepoint,y = ct_perc_time, fill = anno_cell_type_lv2)) + -->
<!--     stat_summary( -->
<!--       fun.y = mean, -->
<!--       geom = "bar", -->
<!--       width = 1, -->
<!--       color = "black") + -->
<!--   geom_beeswarm(size = 2.5, pch = 21, color = "black", fill= "white") + -->
<!--   facet_grid(. ~ anno_cell_type_lv2) + -->
<!--   theme_bw() + -->
<!--   theme(axis.title = element_text(face="bold")) + -->
<!--   theme(axis.text.x = element_text(size = 14,angle = 45, vjust = 0.5, hjust=1), -->
<!--         strip.text.x = element_text(size = 14, colour = "black", angle = 90, face = "bold"), -->
<!--         strip.background = element_blank(), -->
<!--         legend.position = "none") +  -->
<!--   labs(x = "", -->
<!--        y = "% total cells") + -->
<!--   scale_fill_manual(values = named_colors) -->

<!-- ct_time_barplot_v2 -->
<!-- save_plot(ct_time_barplot_v2,filename = here("./plots/mol_cart.Figure_2.ct_percentage.pdf"), -->
<!--           base_height = 6, -->
<!--           base_asp = 2) -->
<!-- ``` -->

<!-- <!-- # Figure 2B: Misty gains --> -->

<!-- <!-- ```{r} --> -->
<!-- <!-- misty.results <- collect_results("./data/results_cts_100.sqm") --> -->
<!-- <!-- ``` --> -->

<!-- <!-- ```{r} --> -->
<!-- <!-- gains <- misty.results$improvements %>% --> -->
<!-- <!--   subset(measure == "gain.R2") %>% --> -->
<!-- <!--   separate(sample, into = c("smpl","time","replicate","slide") , sep="_", remove = FALSE) --> -->

<!-- <!-- gains$time <- factor(gains$time, --> -->
<!-- <!--                      levels = c("control","4h","2d","4d")) --> -->

<!-- <!-- gains <- subset(gains,target %in% c("Cardiomyocytes.Nppa.","Myeloid.cells")) --> -->

<!-- <!-- gains$target <- gsub("\\."," ",gains$target) --> -->
<!-- <!-- gains$target <- factor(gains$target, --> -->
<!-- <!--                        levels = c("Cardiomyocytes Nppa ","Myeloid cells")) --> -->

<!-- <!-- gains_plot <-  ggplot(gains,aes(time,value, fill = time)) + --> -->
<!-- <!--   stat_summary( --> -->
<!-- <!--       fun.y = mean, --> -->
<!-- <!--       geom = "errorbar", --> -->
<!-- <!--       aes(ymax = ..y.., ymin = ..y..), --> -->
<!-- <!--       width = 0.6, --> -->
<!-- <!--       size = 1, --> -->
<!-- <!--       color = "black") + --> -->
<!-- <!--   geom_beeswarm(size = 3, pch = 21, color = "black", aes(fill = time)) + --> -->
<!-- <!--   theme(axis.text.x = element_text(angle = 45, hjust = 1)) + --> -->
<!-- <!--   labs(x = "Target", --> -->
<!-- <!--        y = "Gains R2") +  --> -->
<!-- <!--   facet_grid(.~ target) + --> -->
<!-- <!--   scale_fill_brewer(palette = "Dark2") + --> -->
<!-- <!--   theme(legend.position = "none") --> -->

<!-- <!-- gains_plot --> -->

<!-- <!-- save_plot(gains_plot,filename = here("./figures/mol_cart.Figure_2.misty_gains.pdf"), --> -->
<!-- <!--           base_height = 4.5, --> -->
<!-- <!--           base_asp = 2) --> -->
<!-- <!-- ``` --> -->


<!-- <!-- ```{r} --> -->
<!-- <!-- dbDisconnect(misty.results) --> -->
<!-- <!-- ``` --> -->


<!-- # Figure 2C: Nppa distribution across tissue -->

<!-- ```{r} -->
<!-- expression_plot_list <- list() -->

<!-- samples <- c("sample_control_r1_s1","sample_4h_r1_s1", -->
<!--              "sample_2d_r2_s1","sample_4d_r1_s1") -->

<!-- cluster_of_int <- "Cardiomyocytes_Nppa+" -->
<!-- for(this_sample in samples){ -->
<!--     pt_size <- 0.6 -->
<!--     sample_object <- subset(seurat_object,sample_ID == this_sample) -->
<!--     meta <- sample_object@meta.data -->
<!--     time <- unique(sample_object$timepoint) -->

<!--     highlight_plot <- ggplot(meta,aes(Y_centroid,X_centroid)) + -->
<!--       geom_point(data = subset(meta,!seurat_clusters %in% cluster_of_int),color = "darkgrey", size = pt_size) + -->
<!--       # geom_point(data = subset(meta,seurat_clusters %in% cluster_of_int),aes(color = seurat_clusters), size = pt_size) + -->
<!--       geom_point(data = subset(meta,anno_cell_type_lv2 == cluster_of_int),color = "#6A33C2", size = 1) + -->
<!--       #theme_classic() + -->
<!--       labs(x = "Spatial 1", -->
<!--            y = "Spatial 2", -->
<!--            title = time) + -->
<!--       theme(axis.ticks = element_blank(), -->
<!--             axis.text = element_blank(), -->
<!--             legend.position = "right") -->

<!--     expression_plot_list[[this_sample]] <- highlight_plot -->
<!-- } -->

<!-- time_plot <- wrap_plots(expression_plot_list, nrow = 1, ncol = 4) -->
<!--   print(time_plot) -->
<!-- time_plot -->

<!-- filename <- paste("./figures/mol_cart.Nppa_distribution.png",sep = "") -->
<!-- save_plot(time_plot, -->
<!--         filename = filename, -->
<!--         base_height = 3, -->
<!--         base_asp = 2.5) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- expression_plot_list <- list() -->

<!-- samples <- c("sample_control_r1_s1","sample_4h_r1_s1", -->
<!--              "sample_2d_r2_s1","sample_4d_r1_s1") -->

<!-- cluster_of_int <- "Myeloid_cells" -->
<!-- for(this_sample in samples){ -->
<!--     pt_size <- 0.6 -->
<!--     sample_object <- subset(seurat_object,sample_ID == this_sample) -->
<!--     meta <- sample_object@meta.data -->
<!--     time <- unique(sample_object$timepoint) -->

<!--     highlight_plot <- ggplot(meta,aes(Y_centroid,X_centroid)) + -->
<!--       geom_point(data = subset(meta,!seurat_clusters %in% cluster_of_int),color = "darkgrey", size = pt_size) + -->
<!--       # geom_point(data = subset(meta,seurat_clusters %in% cluster_of_int),aes(color = seurat_clusters), size = pt_size) + -->
<!--       geom_point(data = subset(meta,anno_cell_type_lv2 == cluster_of_int),color = "#565656", size = 1) + -->
<!--       #theme_classic() + -->
<!--       labs(x = "Spatial 1", -->
<!--            y = "Spatial 2", -->
<!--            title = time) + -->
<!--       theme(axis.ticks = element_blank(), -->
<!--             axis.text = element_blank(), -->
<!--             legend.position = "right") -->

<!--     expression_plot_list[[this_sample]] <- highlight_plot -->
<!-- } -->

<!-- time_plot <- wrap_plots(expression_plot_list, nrow = 1, ncol = 4) -->
<!--   print(time_plot) -->
<!-- time_plot -->

<!-- filename <- paste("./figures/mol_cart.Myeloid_distribution.png",sep = "") -->
<!-- save_plot(time_plot, -->
<!--         filename = filename, -->
<!--         base_height = 3, -->
<!--         base_asp = 2.5) -->
<!-- ``` -->

