---
title: "Supplementary Figure 4"
author: "FloWuenne"
date: "2023-06-12"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(vroom)
library(dplyr, warn.conflicts = FALSE)
library(tibble, warn.conflicts = FALSE)
library(tidyverse)
library(ggpubr)
library(cowplot)
library(here)
library(ggbeeswarm)

source("./code/functions.R")
```

# Introduction

```{r}
# Load data
qc_dir <- "../data/nf-core_molkart/molkartqc"
files <- fs::dir_ls(path = qc_dir, glob = "*csv")
qc_data <- vroom(files)
qc_data <- qc_data %>%
  separate(sample_id,
           into = c("string","time","replicate","slide","segmentation"),
           remove = TRUE) %>%
  mutate("sample_ID" = paste(string,time,replicate,slide,sep= "_"))

qc_data$avg_area <- qc_data$avg_area *0.138 * 0.138

qc_data$time  <- factor(qc_data$time,
                        levels = c("control","4h","2d","4d"))

qc_data$segmentation_method <- factor(qc_data$segmentation_method,
                                      levels = c("mesmer","ilastik","cellpose"
                                                 ))

final_samples <- c("sample_control_r1_s1","sample_control_r2_s1",
                   "sample_4h_r1_s1","sample_4h_r2_s2",
                   "sample_2d_r1_s1","sample_2d_r2_s1",
                   "sample_4d_r1_s2","sample_4d_r2_s1")

qc_data <- subset(qc_data,sample_ID %in% final_samples)

qc_data <- qc_data %>%
  pivot_longer(total_cells:spot_assign_percent,
               names_to = "group",
               values_to = "values") %>%
  subset(group %in% c("avg_area","spot_assign_per_cell","spot_assign_percent","total_cells"))
```

# Plot the data

```{r}
qc_data$group <- gsub("avg_area",paste("Average area (","\U00B5","m2)",sep=""),qc_data$group)
qc_data$group <- gsub("spot_assign_per_cell","Spots / cell",qc_data$group)
qc_data$group <- gsub("spot_assign_percent","% spots in cells",qc_data$group)
qc_data$group <- gsub("total_cells","Total # cells ",qc_data$group)

spots_assigned <- ggplot(qc_data,aes(segmentation_method, y= values, group = segmentation_method)) +
  geom_boxplot(aes(color = segmentation_method, fill = segmentation_method),
               outlier.size = 0, alpha = 0.3) +
  # coord_flip() +
  scale_fill_brewer(palette = "Dark2") +
  scale_color_brewer(palette = "Dark2") +
  scale_x_discrete(labels=c("cellpose" = "Cellpose 2",
                            "ilastik" = "Ilastik Multicut",
                            "mesmer" = "Mesmer")) +
  labs(x = "") +
  theme(legend.position = "none") +
  facet_wrap(~ group, scales = "free") +
  theme(plot.background = element_rect(fill = "white")) +
  geom_point(size = 3.5, aes(fill = segmentation_method), color = "black" ,
             pch = 21, alpha = 1) +
  panel_border()

spots_assigned

save_plot(filename = here("./plots/Supplementary_figure_3.segmentation_metrics.png"),
          plot = spots_assigned,
          base_height = 2.5,
          base_width = 5)


save_plot(filename = here("./plots/Supplementary_figure_3.segmentation_metrics.pdf"),
          plot = spots_assigned,
          base_height = 6)
```
