---
title: "molkart.Figure1"
author: "FloWuenne"
date: "2023-08-11"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r}
library(tidyverse)
library(cowplot)
library(Seurat)
library(SCpubr)
library(pals)
library(patchwork)
library(ggbeeswarm)
library(viridis)
library(ggdark)

source("./code/functions.R")
```


```{r}
## If the object has already been computed
seurat_object <-  readRDS(file = "./output/molkart/molkart.seurat_object.rds")
```

```{r}
## How many cells did we recover per sample?
cells_per_sample <- seurat_object@meta.data %>%
  group_by(sample_ID) %>%
  tally() %>%
  ungroup()

mean(cells_per_sample$n)
```

# Umap plot

```{r}
seurat_object@meta.data$anno_cell_type_lvl2 <- gsub("_"," ",seurat_object@meta.data$anno_cell_type_lvl2)
# 
# pal.bands(alphabet, alphabet2, cols25, glasbey, kelly, polychrome, 
#   stepped, tol, watlington, tableau20,
#   show.names=FALSE)

cell_types <- unique(seurat_object@meta.data$anno_cell_type_lvl2)
colors <- kelly(n=22)
## Replace white ish color as we can't see it well in plots

# Create a named vector for cell_types and colors to use in plots later

# Code from scanpy 
# https://github.com/scverse/scanpy/commit/58fae77cc15893503c0c34ce0295dd6f67af2bd7
vega10_scanpy <- c("#1f77b4","#ff7f0e","#2ca02c","#d62728","#9467bd","#8c564b","#e377c2","#7f7f7f","#bcbd22","#17becf")


# Use vega10 color palette for clusters
# named_colors <- c("Cardiac fibroblasts" = "#1f77b4",
#                   "Cardiomyocytes" = "#d62728",
#                   "Cardiomyocytes Nppa+" = "#ff7f0e",
#                   "Endocardial cells" = "#17becf",
#                   "Endothelial cells" = "#8c564b",
#                   "Lymphatic endothelial cells" = "lightgrey",
#                   "Lymphoid cells" = "#bcbd22",
#                   "Myeloid cells" = "#2ca02c",
#                   "Pericytes" = "#e377c2",
#                   "Smooth muscle cells" = "#9467bd"
#                   )

named_colors <- c("Cardiac fibroblasts" = "#1f77b4",
                  "Cardiomyocytes" = "#ff7697",
                  "Cardiomyocytes Nppa+" = "#ff9966",
                    "Endocardial cells" = "#17becf",
                    "Endothelial cells" = "#8c564b",
                  
                    "Lymphoid cells" = "#bcbd22",
                    "Myeloid cells" = "#2ca02c",
                    "Pericytes" = "#9467bd",
                    "Smooth muscle cells" = "#e377c2")
```

## Figure 1C : UMAP plot of cell types

```{r}
## Single total UMAP plot

library(scCustomize)
## Set color palette
Idents(object = seurat_object) <- "anno_cell_type_lvl2"

umap_plot <- SCpubr::do_DimPlot(sample = seurat_object,
                                label = FALSE, label.box = TRUE,
                                group.by = "anno_cell_type_lvl2",
                                repel = TRUE, legend.position = "none", 
                                colors.use = named_colors, 
                                plot_cell_borders = TRUE,
                                plot_density_contour = FALSE, plot.axes = FALSE, raster.dpi = 300, shuffle = FALSE, pt.size = 0.4,
                                legend.icon.size = 5, legend.byrow = TRUE) +
  theme(legend.text = element_text(size = 18))

umap_plot

# save_plot(umap_plot,
#           file = "./plots/Figure1.umap_plot.pdf",
#           base_height = 6)
# 
# 
# save_plot(umap_plot,
#           file = "./plots/Figure1.umap_plot.png",
#           base_height = 6)
```

```{r}
## UMAP split by time
library(scCustomize)
## Set color palette
Idents(object = seurat_object) <- "anno_cell_type_lvl2"
seurat_object_ctrl <- subset(seurat_object, timepoint == "control")
seurat_object_4h <- subset(seurat_object, timepoint == "4h")
seurat_object_2d <- subset(seurat_object, timepoint == "2d")
seurat_object_4d <- subset(seurat_object, timepoint == "4d")

umap_plot_control <- SCpubr::do_DimPlot(sample = seurat_object_ctrl,
                                label = FALSE, label.box = FALSE,
                                group.by = "anno_cell_type_lvl2",
                                repel = TRUE, legend.position = "none", 
                                colors.use = named_colors, 
                                plot_cell_borders = TRUE,
                                plot_density_contour = FALSE, plot.axes = FALSE,
                                raster.dpi = 300, shuffle = FALSE, pt.size = 0.4,
                                legend.icon.size = 5)

umap_plot_4h <- SCpubr::do_DimPlot(sample = seurat_object_4h,
                                label = FALSE, label.box = FALSE,
                                group.by = "anno_cell_type_lvl2",
                                repel = TRUE, legend.position = "none", 
                                colors.use = named_colors, 
                                plot_cell_borders = TRUE,
                                plot_density_contour = FALSE, plot.axes = FALSE,
                                raster.dpi = 300, shuffle = FALSE, pt.size = 0.4,
                                legend.icon.size = 5)

umap_plot_2d <- SCpubr::do_DimPlot(sample = seurat_object_2d,
                                label = FALSE, label.box = FALSE,
                                group.by = "anno_cell_type_lvl2",
                                repel = TRUE, legend.position = "none", 
                                colors.use = named_colors, 
                                plot_cell_borders = TRUE,
                                plot_density_contour = FALSE, plot.axes = FALSE,
                                raster.dpi = 300, shuffle = FALSE, pt.size = 0.4,
                                legend.icon.size = 5)

umap_plot_4d <- SCpubr::do_DimPlot(sample = seurat_object_4d,
                                label = FALSE, label.box = FALSE,
                                group.by = "anno_cell_type_lvl2",
                                repel = TRUE, legend.position = "none", 
                                colors.use = named_colors, 
                                plot_cell_borders = TRUE,
                                plot_density_contour = FALSE, plot.axes = FALSE,
                                raster.dpi = 300, shuffle = FALSE, pt.size = 0.4,
                                legend.icon.size = 5)
```

```{r}
full_plot <- umap_plot_control | umap_plot_4h | umap_plot_2d | umap_plot_4d

save_plot(full_plot,
          file = "./plots/Figure1.umap_plot.png",
          base_height = 4,
          base_asp = 4,
          dpi = 300)

save_plot(full_plot,
          file = "./plots/Figure1.umap_plot.pdf",
          base_height = 4,
          base_asp = 4,
          dpi = 300)
```

# Figure 1F : Overview of spatial distribution of cell types within 1 sample

```{r}
sample_highlight <- "sample_2d_r2_s1"
#sample_highlight <- "sample_control_r2_s1"

meta_sample <- subset(seurat_object@meta.data,sample_ID == sample_highlight)

full_overview <-  ggplot(meta_sample,aes(X_centroid,Y_centroid)) +
    geom_point(aes(color = anno_cell_type_lvl2),size = 0.6) +
    theme_classic() +
    dark_theme_void() +
    labs(x = "Spatial 1",
         y = "Spatial 2") +
    theme(axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.text = element_blank(),
          axis.line = element_blank(),
          legend.position = "none") +
    scale_color_manual(values = named_colors)

# Custom function to return an empty string for each label
blank_labels <- function(value) {
  return(rep("", length(value)))
}

cell_type_views <- ggplot(meta_sample,aes(X_centroid,Y_centroid)) +
  dark_theme_void() +
  geom_point(aes(color = anno_cell_type_lvl2),size = 0.4) +
  scale_color_manual(values = named_colors) +
  facet_wrap(~ anno_cell_type_lvl2,labeller = as_labeller(blank_labels)) +
  theme(strip.text = element_text(size = 18, color = "white"),
        legend.position = "none"
        )



full_plot <- (full_overview | cell_type_views) +   plot_layout(ncol = 2,widths = c(0.6, 1))

full_plot
save_plot(full_plot,filename = here("./plots/molkart.Figure_1.spatial_distribution.pdf"),
          base_height = 4,
          base_asp = 2)
```

```{r}
library(ggplot2)
library(dplyr)

# Assuming meta_sample is your data frame and named_colors is your color vector

# Get unique cell types
unique_cell_types <- sort(unique(meta_sample$anno_cell_type_lvl2))

# Loop through each cell type and generate a plot
plots <- lapply(unique_cell_types, function(cell_type) {
  
  # Generate the plot
  ## Add a line of blank space on top of the plot
  p <- ggplot(meta_sample, aes(x = X_centroid, y = 
                                 Y_centroid)) +
    dark_theme_void() +
    geom_point(data = subset(meta_sample,anno_cell_type_lvl2 != cell_type),
               size = 0.6, color = "white") +
    geom_point(data = subset(meta_sample,anno_cell_type_lvl2 == cell_type),
               size = 0.6, 
               aes(color = anno_cell_type_lvl2)) +
    scale_color_manual(values = named_colors) +
    theme(legend.position = "none")  # Hide legend or adjust as needed
    # Add a line of blank space on top of the plot
    p <- p + theme(plot.margin = margin(0.5,0,0,0, "cm"))
  
  # Return the plot
  return(p)
})

# Optionally, print plots or save them to files
# for (p in plots) print(p)
cell_type_views <- wrap_plots(plots, nrow = 3, ncol = 3)

save_plot(full_overview,
          filename = "./plots/molkart.Figure_1.spatial_distribution.full.pdf",
          base_height = 5,
          base_asp = 0.9)

save_plot(cell_type_views,
          filename = "./plots/molkart.Figure_1.spatial_distribution.cts.pdf",
          base_height = 5,
          base_asp = 1.3)
```


```{r}
# Plot with labels
 ggplot(meta_sample,aes(X_centroid,Y_centroid)) +

  geom_point(aes(color = anno_cell_type_lvl2),size = 0.5) +
  scale_color_manual(values = named_colors) +
  facet_wrap(~ anno_cell_type_lvl2) +
  theme(strip.text = element_text(size = 18, color = "white"),
        legend.position = "none"
        )
```

## Additional plots 

# Figure 1D: Marker Dotplot (deprecated)

```{r}
harmony_object <- PrepSCTFindMarkers(seurat_object, assay = "SCT", verbose = TRUE)
harmony_markers <- FindAllMarkers(seurat_object, logfc.threshold = 0.5, only.pos = TRUE)
```


```{r}
## For the Dotplot, we want the same order as for the Umap plot, so we have to reverse it
seurat_object$anno_cell_type_lvl2 <- factor(seurat_object$anno_cell_type_lvl2,
                                            levels = rev(sort(unique(seurat_object$anno_cell_type_lvl2))))

genes <- c("Pdgfra","Pln","Nppa","Npr3","Kdr","Sell",
           "C1qa","Colec11","Myh11")


dotplot <- DotPlot(seurat_object, group.by = "anno_cell_type_lvl2", features = genes) +
  geom_point(aes(size=pct.exp), shape = 21, colour="black", stroke=0.5) +
  scale_colour_viridis(option="viridis", direction = 1) +
  theme(axis.title =  element_blank(),
        axis.text.x = element_text(size = 18, angle = 45, hjust=1),
        axis.text.y = element_text(size = 18),
        legend.position = "right", 
        legend.text = element_text(size = 18))
dotplot

save_plot(dotplot,
          file = "./plots/Figure1.dotplot.pdf",
          base_height = 6,
          base_asp = 1.8)
```


<!-- ### Spatial plot with all samples and cell types -->

<!-- ```{r} -->
<!-- meta <- seurat_object@meta.data -->

<!-- expression_plot_list <- list() -->
<!-- samples <- c("sample_control_r1_s1","sample_4h_r1_s1", -->
<!--              "sample_2d_r1_s1","sample_4d_r1_s1", -->
<!--              "sample_control_r2_s1","sample_4h_r2_s2", -->
<!--              "sample_2d_r2_s1","sample_4d_r2_s1") -->

<!-- for(this_sample in samples){ -->
<!--   pt_size <- 0.3 -->
<!--   cluster_of_int <- c(16,19) -->
<!--   sample_object <- subset(meta,sample_ID == this_sample) -->

<!--   highlight_plot <- ggplot(sample_object,aes(X_centroid,Y_centroid)) + -->
<!--     geom_point(aes(color = anno_cell_type_lvl2),size = pt_size) + -->
<!--     theme_void() + -->
<!--     theme(axis.ticks = element_blank(), -->
<!--             axis.text = element_blank(), -->
<!--             legend.position = "none") + -->
<!--     scale_color_manual(values =named_colors) -->

<!--     expression_plot_list[[this_sample]] <- highlight_plot -->

<!-- } -->
<!-- ``` -->

<!-- ```{r} -->
<!-- wrap_plots(expression_plot_list, nrow = 2, ncol = 4) -->
<!-- ``` -->

<!-- ### Quantification of abundance changes for select cell types -->

<!-- ```{r} -->
<!-- metadata <- seurat_object@meta.data -->

<!-- cell_type_proportions_per_sample <- metadata %>% -->
<!--   group_by(anno_cell_type_lvl2,timepoint,sample_ID) %>% -->
<!--   tally() %>% -->
<!--   ungroup() %>% -->
<!--   group_by(timepoint) %>% -->
<!--   mutate("ct_perc_time" = n / sum(n)) %>% -->
<!--   ungroup() -->

<!-- ## Mean and points version -->
<!-- cell_type_proportions_per_sample$anno_cell_type_lvl2 <- gsub("_"," ",cell_type_proportions_per_sample$anno_cell_type_lvl2) -->

<!-- ## Set order of cell types in plot from most abundant to least abundant -->
<!-- total_cells <- cell_type_proportions_per_sample %>% -->
<!--   group_by(anno_cell_type_lvl2) %>% -->
<!--   summarise("total_cells" = sum(n)) %>% -->
<!--   arrange(desc(total_cells)) -->

<!-- cell_type_proportions_per_sample$anno_cell_type_lvl2 <- factor(cell_type_proportions_per_sample$anno_cell_type_lvl2, -->
<!--        levels = total_cells$anno_cell_type_lvl2) -->

<!-- ## Set color palette for cell-types in molecular cartography data -->
<!-- cell_types <- unique(unique(cell_type_proportions_per_sample$anno_cell_type_lvl2)) -->
<!-- colors <- cols25(n=length(cell_types)) -->
<!-- named_colors <- colors -->
<!-- names(named_colors) <- cell_types -->

<!-- cell_types_oi <- c("Cardiomyocytes","Cardiac fibroblasts","Cardiomyocytes Nppa+","Myeloid cells") -->
<!-- cell_type_proportions_per_sample <- subset(cell_type_proportions_per_sample, -->
<!--                                            anno_cell_type_lvl2 %in% cell_types_oi) -->

<!-- ct_time_barplot_v2 <- ggplot(cell_type_proportions_per_sample,aes(x = timepoint,y = ct_perc_time, fill = anno_cell_type_lvl2)) + -->
<!--     stat_summary( -->
<!--       fun.y = mean, -->
<!--       geom = "bar", -->
<!--       width = 1, -->
<!--       color = "black") + -->
<!--   geom_beeswarm(size = 2.5, pch = 21, color = "black", fill= "white") + -->
<!--   facet_grid(. ~ anno_cell_type_lvl2) + -->
<!--   theme_bw() + -->
<!--   theme(axis.title = element_text(face="bold")) + -->
<!--   theme(axis.text.x = element_text(size = 14,angle = 45, vjust = 0.5, hjust=1), -->
<!--         strip.text.x = element_text(size = 14, colour = "black", angle = 90, face = "bold"), -->
<!--         strip.background = element_blank(), -->
<!--         legend.position = "none") +  -->
<!--   labs(x = "", -->
<!--        y = "% total cells") + -->
<!--   scale_fill_manual(values = named_colors) -->

<!-- ct_time_barplot_v2 -->
<!-- ``` -->


<!-- ### Spatial plot showing abundance change over time -->

<!-- ```{r} -->
<!-- samples <- c("sample_control_r1_s1","sample_4h_r1_s1", -->
<!--              "sample_2d_r2_s1","sample_4d_r2_s1") -->

<!-- expression_plot_list <- list() -->
<!-- time_plot_list <- list() -->

<!-- colors_used <- named_colors[cell_types_oi] -->

<!-- cluster_of_int <- 15 -->
<!-- for(cluster_of_int in cell_types_oi){ -->
<!--   print(cluster_of_int) -->
<!--   color_use <- colors_used[[cluster_of_int]] -->
<!--   for(this_sample in samples){ -->
<!--     pt_size <- 0.1 -->
<!--     sample_object <- subset(seurat_object,sample_ID == this_sample) -->
<!--     meta <- sample_object@meta.data -->

<!--     highlight_plot <- ggplot(meta,aes(Y_centroid,X_centroid)) + -->
<!--       geom_point(data = subset(meta,!seurat_clusters %in% cluster_of_int),color = "darkgrey", size = pt_size) + -->
<!--       geom_point(data = subset(meta,gsub("_"," ",anno_cell_type_lvl2) == cluster_of_int),color = color_use, size = pt_size * 2) + -->
<!--       theme_classic() + -->
<!--       labs(x = "Spatial 1", -->
<!--            y = "Spatial 2") + -->
<!--       theme(axis.ticks = element_blank(), -->
<!--             axis.text = element_blank(), -->
<!--             legend.position = "right") -->

<!--     expression_plot_list[[this_sample]] <- highlight_plot -->
<!--   } -->
<!--   time_plot <- wrap_plots(expression_plot_list, nrow = 1, ncol = 4)  + plot_layout(guides = 'collect') + plot_annotation(cluster_of_int,theme=theme(plot.title=element_text(hjust=0.5))) -->
<!--   time_plot_list[[cluster_of_int]] <- time_plot -->
<!-- } -->

<!-- final_plot <- wrap_plots(time_plot_list, nrow = length(cell_types_oi), ncol = 1)  + plot_layout(guides = 'collect') -->
<!-- final_plot -->
<!-- ``` -->

<!-- ### Plot target cell types from one time point next to each other -->

<!-- ```{r} -->
<!-- samples <- c("sample_control_r1_s1","sample_2d_r1_s1") -->

<!-- expression_plot_list <- list() -->
<!-- time_plot_list <- list() -->

<!-- cell_types_oi <- c("Cardiac fibroblasts","Cardiomyocytes Nppa+","Myeloid cells 1") -->
<!-- colors_used <- named_colors[cell_types_oi] -->


<!-- for(cluster_of_int in cell_types_oi){ -->
<!--   print(cluster_of_int) -->
<!--   color_use <- colors_used[[cluster_of_int]] -->
<!--   if(cluster_of_int == "Endocardial cell"){color_use <- "red"} -->
<!--   pt_size <- 0.2 -->
<!--     sample_object <- subset(seurat_object,sample_ID == "sample_4d_r1_s1") -->
<!--     meta <- sample_object@meta.data -->

<!--     highlight_plot <- ggplot(meta,aes(Y_centroid,X_centroid)) + -->
<!--       geom_point(data = subset(meta,!seurat_clusters %in% cluster_of_int),color = "darkgrey", size = pt_size) + -->
<!--       geom_point(data = subset(meta,gsub("_"," ",anno_cell_type_lvl2) == cluster_of_int),color = color_use, size = pt_size * 4) + -->
<!--       theme_classic() + -->
<!--       labs(x = "Spatial 1", -->
<!--            y = "Spatial 2", -->
<!--            title = cluster_of_int) + -->
<!--       theme(axis.ticks = element_blank(), -->
<!--             axis.text = element_blank(), -->
<!--             legend.position = "right") -->

<!--     expression_plot_list[[cluster_of_int]] <- highlight_plot -->
<!-- } -->

<!-- cell_type_plot <- wrap_plots(expression_plot_list, nrow = 1, ncol = 3)  + plot_layout(guides = 'collect') -->
<!-- cell_type_plot -->
<!-- ``` -->




# Figure 1E: Cell type changes over time (deprecated)

```{r}
# ct_time_barplot_v2 <- ggplot(cell_type_proportions_per_sample,aes(x = timepoint,y = ct_perc_time, fill = anno_cell_type_lvl2)) +
#     stat_summary(
#       fun = mean,
#       geom = "bar",
#       width = 1,
#       color = "black") +
#   geom_beeswarm(size = 2.5, pch = 21, color = "black", fill= "white") +
#   facet_grid(. ~ anno_cell_type_lvl2) +
#   theme_bw() +
#   theme(axis.title = element_text(face="bold")) +
#   theme(axis.text.x = element_text(size = 14,angle = 45, vjust = 0.5, hjust=1),
#         strip.text.x = element_text(size = 14, colour = "black", angle = 90, face = "bold"),
#         strip.background = element_blank(),
#         legend.position = "none") + 
#   labs(x = "",
#        y = "% total cells") +
#   scale_fill_manual(values = named_colors)
# 
# ct_time_barplot_v2
# save_plot(ct_time_barplot_v2,filename = here("./plots/mol_cart.Figure_2.ct_percentage.pdf"),
#           base_height = 6,
#           base_asp = 2)
```

```{r}
## Reverese order again for the other plots
seurat_object$anno_cell_type_lvl2 <- factor(seurat_object$anno_cell_type_lvl2,
                                            levels = rev(sort(unique(seurat_object$anno_cell_type_lvl2))))
```
