---
title: "figures.supplementary_figure_X.proteomics_qc"
author: "FloWuenne"
date: "2023-06-26"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

(future.globals.maxSize = 4000 * 1024^5)

library(tidyverse)
library(data.table)
library(here)
library(ggrepel)
library(patchwork)
library(ggVennDiagram)
library(viridis)
library(heatmaply)
library(ggsignif)
library(ggrepel)
library(ggbeeswarm)

source("./code/functions.R")
```

This supplementary figure contains QC plots for the proteomic data analysis.

```{r}
## load data
metadata_counts <- fread("./output/proteomics/proteomics.protein_missing_stats.tsv")
```


# Subfigure A - Total proteins identified per group

```{r}
## Summarize observations across group
metadata_counts_stat <- data_summary(metadata_counts,
                                     varname = "wo_cont", groupnames = c("group"))

avg_proteins <- mean(metadata_counts$wo_cont)
avg_proteins <- sd(metadata_counts$wo_cont)

metadata_counts_stat$group <- factor(metadata_counts_stat$group,
                                     levels = c("MI_IZ","MI_remote","control"))

## Barplot to show the number of proteins detected per group (excluding contaminants)
n_prot_plot <- ggplot(metadata_counts_stat,aes(group,wo_cont)) +
  geom_bar(aes(fill = group),stat="identity", color="black", 
           position=position_dodge()) +
  geom_point(data = metadata_counts, aes(group,wo_cont),
             fill = "white",pch = 21, color= "black",size = 4) +
  geom_errorbar(aes(ymin=wo_cont, ymax=wo_cont+sd), width=.2,
                 position=position_dodge(.9)) + 
  coord_flip() +
  scale_fill_manual(values = proteome_palette,
                    labels = c("Control","MI_remote","MI_IZ")) +
  labs(x = "",
       y = "Proteins detected") +
  theme(legend.position = "none")

n_prot_plot
```


# Subfigure B - % missing proteins vs number of nuclei collected


```{r}
metadata_counts$group <- factor(metadata_counts$group,
                                levels = c("control","MI_remote","MI_IZ"))

missingness_plot <- ggplot(metadata_counts,aes(missingness,n_nuclei, label = sample)) +
  geom_point(pch = 21, size = 5,aes(fill = group)) +
  scale_fill_manual(values = proteome_palette,
                    labels = c("Control","MI_remote","MI_IZ")) +
  geom_label_repel() +
  labs(x = "% missing values",
       y = "# nuclei in tissue collected",
       fill = "Group") +
  theme(legend.position = "top")
missingness_plot

```

# Subfigure C - % variance explained by PCs

```{r}
pca_res <- readRDS("./output/proteomics/proteomics.pca_res.rds")

sdev <- pca_res$sdev[1:5]
var_explained <- data.frame(PC = paste0("PC",1:5),
                            var_expl = (sdev)^2/sum((sdev)^2)
                            )

pca_var <- ggplot(var_explained,aes(PC,var_expl)) +
  geom_bar(stat = "identity", color = "black", fill = "grey30") +
  geom_text(aes(label = paste(100*round(var_expl,2),sep = "")), vjust=1.4, color = "white", size =6) +
  labs(x = "Principal components",
       y = "% Variance explained")

pca_var
```


# Subfigure D - Upset plot for shared proteins between conditions
```{r}
library(ggplot2)
library(ComplexUpset)

## Load limma results and subset for significantly differential proteins between conditions
limma_res <- fread("./output/proteomics/proteomics.limma.full_statistics.tsv")
limma_res_sig <- subset(limma_res,adj.P.Val <= 0.05)
limma_res_sig <- limma_res_sig %>%
  select(gene,analysis) %>%
  mutate(value = 1) %>%
  # Reshape the data frame so that each gene has 1 row entry for each comparison
  pivot_wider(names_from = analysis, 
              values_from = value, 
              values_fill = list(value = 0)) %>%
  # Sum rows by gene
  group_by(gene) %>%
  summarise_all(sum) %>%
  ungroup()
              
analysis_groups <- c("MI_IZ_vs_control","MI_remote_vs_control","MI_IZ_vs_MI_remote")
upset_plot <- upset(limma_res_sig, analysis_groups , name='Comparison',
                    width_ratio=0.1,
                    set_sizes=(
                      upset_set_size()
        + theme(axis.text.x=element_text(angle=90))
    ))
upset_plot
```

# Assemble final figure

```{r,fig.height = 8, fig.width = 10}
supp_figure_X <- n_prot_plot + missingness_plot + pca_var + wrap_elements(upset_plot)

supp_figure_X <- supp_figure_X + 
  plot_layout(nrow = 2,ncol =2 , widths = c(1,2)) +
  plot_annotation(tag_levels = 'a') & 
  theme(plot.tag = element_text(size = 25)) &
  theme(plot.background = element_rect(fill = "white"))

supp_figure_X

save_plot(filename = "./figures/Supplementary_figure_X.proteomics.png",
          plot = supp_figure_X,
          base_height = 8)


save_plot(filename = "./figures/Supplementary_figure_X.proteomics.eps",
          plot = supp_figure_X,
          base_height = 8)
```



<!-- # Volcano plot of MI_IZ vs control -->

<!-- ```{r} -->
<!-- iz_control <- subset(limma_res, analysis == "MI_IZ_vs_control") -->
<!-- iz_control <- iz_control %>% -->
<!--   arrange(desc(logFC)) -->

<!-- prot_2label <- "" -->
<!-- prot_2label <- subset(iz_control, adj.P.Val < 0.05)[1:10,]$gene -->
<!-- prot_2label <- c(prot_2label,tail(subset(iz_control, adj.P.Val < 0.05),1)$gene) -->

<!-- iz_control <- iz_control %>% -->
<!--   mutate("label_protein" = if_else(gene %in% prot_2label, gene,"")) -->

<!-- ## Volcano plot of IZ_remote vs control -->
<!-- iz_control_volc <- plot_pretty_volcano(iz_control,  -->
<!--                                       pt_size = 2, -->
<!--                                       plot_title = "MI_remote vs control", -->
<!--                                       sig_col = "adj.P.Val", -->
<!--                                       sig_thresh = 0.05, -->
<!--                                       col_pos_logFC = proteome_palette[['control']], -->
<!--                                       col_neg_logFC = proteome_palette[['MI_IZ']]) + -->
<!--   geom_label_repel(max.overlaps = 10) -->

<!-- iz_control_volc -->
<!-- ``` -->

<!-- # Volcano plot of MI_remote vs control -->

<!-- ```{r} -->
<!-- remote_control <- subset(limma_res, analysis == "MI_remote_vs_control") -->
<!-- remote_control <- remote_control %>% -->
<!--   arrange(desc(logFC)) -->

<!-- prot_2label <- subset(remote_control, adj.P.Val < 0.05)[1:13,]$gene -->
<!-- prot_2label <- c(prot_2label,tail(subset(remote_control, adj.P.Val < 0.05),1)$gene) -->
<!-- remote_control <- remote_control %>% -->
<!--   mutate("label_protein" = if_else(gene %in% prot_2label, gene,"")) -->

<!-- ## Volcano plot of IZ_remote vs control -->
<!-- remote_control_volc <- plot_pretty_volcano(remote_control,  -->
<!--                                       pt_size = 2, -->
<!--                                       plot_title = "MI_remote vs control", -->
<!--                                       sig_col = "adj.P.Val", -->
<!--                                       sig_thresh = 0.05, -->
<!--                                       col_pos_logFC = proteome_palette[['MI_remote']], -->
<!--                                       col_neg_logFC = proteome_palette[['control']]) + -->
<!--   geom_label_repel() -->

<!-- remote_control_volc -->
<!-- ``` -->


<!-- # Plot candidate protein expressions -->

<!-- ```{r} -->
<!-- vsn_matrix <- fread("./output/proteomics/proteomics.vsn_norm_proteins.tsv") -->

<!-- protein_sub <- vsn_matrix  %>% -->
<!--     dplyr::select(1:11,gene) %>% -->
<!--     pivot_longer(1:11,names_to = "sample", values_to = "exp") %>% -->
<!--     mutate("group" = if_else(grepl("control",sample),"control", -->
<!--                                    if_else(grepl("MI_IZ",sample), -->
<!--                                            "MI_IZ","MI_remote")) -->
<!--     ) -->

<!-- protein_sub$group <- factor(protein_sub$group, -->
<!--                               levels = c("control","MI_remote","MI_IZ")) -->

<!-- goi <- "Vwf" -->
<!-- plot_proteomics_boxplot(norm_table = protein_sub, -->
<!--                         protein = goi) + -->
<!--   geom_signif(comparisons = list(c("MI_IZ","MI_remote")), -->
<!--               tip_length = 0, annotation = subset(limma_res, -->
<!--                                                   analysis == "MI_IZ_vs_MI_remote" & -->
<!--                                                     gene == goi)$adj.P.Val) -->
<!-- ``` -->
