---
title: "Supplementary Figure 7"
author: "Florian Wuennemann"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r}
library(tidyverse)
library(data.table)
library(ggbeeswarm)
library(patchwork)

source("./code/functions.R") 
```


# New b) Immunofluorescence relative abundance of CCR2+ cells in traditional IF


```{r}
if_rel_counts <- fread("./data/Traditional_IF_relative_cell_counts.csv")

colnames(if_rel_counts) <- gsub(" ","_",colnames(if_rel_counts))
if_rel_counts <- if_rel_counts %>%
  pivot_longer(cols = Endo_Pre:BZ_2d,
               names_to = "sample",
               values_to = "cell_count") %>%
  separate(sample, into = c("region","timepoint"), sep = "_")

# Replace abbreviations with full labels
if_rel_counts$region <- gsub("Endo","Endocard",if_rel_counts$region)
if_rel_counts$region <- gsub("Core","Infarct core",if_rel_counts$region)
if_rel_counts$region <- gsub("Epi","Epicard",if_rel_counts$region)
if_rel_counts$region <- gsub("BZ","Border zone",if_rel_counts$region)
if_rel_counts$region <- factor(if_rel_counts$region, levels = c("Endocard","Infarct core","Epicard","Border zone"))

if_rel_counts$timepoint <- gsub("Pre","Control",if_rel_counts$timepoint)
if_rel_counts$timepoint <- gsub("1d","24h",if_rel_counts$timepoint)
if_rel_counts$timepoint <- gsub("2d","2 days",if_rel_counts$timepoint)
if_rel_counts$timepoint <- factor(if_rel_counts$timepoint, levels = c("Control","4h","24h","2 days"))

if_rel_counts <- subset(if_rel_counts,timepoint != "Control")

if_ccr2_relquant <- ggplot(if_rel_counts,aes(timepoint,cell_count)) +
    stat_summary(
      fun.y = mean,
      geom = "bar",
      width = 0.9,
      size = 0.3,
      color = "black",
      fill = "lightgrey") +
  labs(x = "Time",
         y = expression("Cells /"~mm^2)) + 
  geom_beeswarm(size = 2 , pch = 21, color = "black", aes(fill = region)) +
  facet_grid(.~ region) +
  theme(axis.title = element_text(face="bold"),
        legend.position = "none") +
  scale_fill_manual(values = c("#337272","#f0f0f0","#b062c2","#2c95c5")) +
  theme(panel.border = element_rect(color = "black", fill = NA, size = 0.75)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_blank())

save_plot(filename = "./plots/supp_figure_7.tradIF-relative_cell_counts.pdf",
          plot = if_ccr2_relquant,
          base_asp = 3,
          base_height = 4)
```

